version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: techstore-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "2001"
      MYSQL_DATABASE: online_store
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - techstore-network
    command:
      - --default-authentication-plugin=mysql_native_password
      - --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p2001"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: techstore-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: "root"
      DB_PASS: "2001"
      DB_NAME: online_store
      NODE_ENV: production
      JWT_SECRET: your_secret_key_here
      ENCRYPTION_KEY: 12345678901234567890123456789012
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - techstore-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend/auth-app
      dockerfile: Dockerfile
    container_name: techstore-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - techstore-network

networks:
  techstore-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local 